# Usage:
#   
# To build the images:
#   docker compose build
# 
# To start up a specific service:
#   docker compose up -d <service_name>
#
# To open an interactive shell in a running container:
#   docker exec -it <container_name> bash

services:
  # Base image containing dependencies.
  base:
    container_name: ${PROJECT_NAME}-base
    image: ${PROJECT_NAME}:base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:?}
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True
    # runtime: nvidia
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    # deploy: # swarm mode
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  # Overlay image containing the example source code.
  overlay:
    container_name: ${PROJECT_NAME}-overlay
    extends: base
    image: ${PROJECT_NAME}:overlay
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: overlay

  # Developer container
  dev:
    container_name: ${PROJECT_NAME}-dev
    extends: overlay
    image: ${PROJECT_NAME}:dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}

    volumes:
      # Mount the source code
      - ./src:/overlay_ws/src/:rw
      # Mount colcon build artifacts for faster rebuilds
      - ./.colcon/build/:/overlay_ws/build/:rw
      - ./.colcon/install/:/overlay_ws/install/:rw
      - ./.colcon/log/:/overlay_ws/log/:rw
    user: ${USERNAME:-devuser}
    command: bash -c "sudo chmod 777 -R /overlay_ws/ && exec sleep infinity"
  
  #viz:
    #extends: dev
    #command: rviz -d /overlay_ws/src/some_folder/rviz.rviz  